channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - mpi4py=3.0.3
  - pytorch=1.3.1
  - torchvision=0.4.2
  - cudatoolkit=10.0
  - pip
  - pip:
    - gym==0.15.4
    - procgen==0.9.2
    - tensorflow-gpu==1.15.0
    - matplotlib
    - pandas
    - pyyaml
    - pytest # for baselines